#include "hobj_metric_operation.h"

namespace dm
{
	static constexpr const char *s_ObjectOperationTypeStr[underlying(ObjectOperationType::COUNT)] = {
			"UNDEFINED",

			"SOURCE_MANIFEST_POPULATE",
			"SOURCE_MANIFEST_CREATE_ENTRY",
			"SOURCE_MANIFEST_REMOVE_ENTRY",
			"SOURCE_MANIFEST_LOOKUP_ENTRY",
			"SOURCE_MANIFEST_GET_ENTRY",

			"SOURCE_OBJECT_SAVE",
			"SOURCE_OBJECT_DELETE",
			"SOURCE_OBJECT_GET",
			"SOURCE_OBJECT_CREATE",
			"SOURCE_OBJECT_LOAD",
			"SOURCE_OBJECT_UNLOAD",
			"SOURCE_OBJECT_SERIALIZE",
			"SOURCE_OBJECT_DESERIALIZE",

			"SOURCE_OBJECT_FILE_OPEN",
			"SOURCE_OBJECT_FILE_CLOSE",

			"REGISTRY_MANIFEST_POPULATE",
			"REGISTRY_MANIFEST_CREATE_ENTRY",
			"REGISTRY_MANIFEST_DELETE_ENTRY",
			"REGISTRY_MANIFEST_LOOKUP_ENTRY",
			"REGISTRY_MANIFEST_GET_ENTRY",

			"REGISTRY_OBJECT_SAVE",
			"REGISTRY_OBJECT_DELETE",
			"REGISTRY_OBJECT_GET",
			"REGISTRY_OBJECT_CREATE"};

	const char *object_operation_type_to_string(ObjectOperationType type)
	{
		return s_ObjectOperationTypeStr[underlying(type)];
	}
}
